name: Shell Commands

on:  [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: tries to echo a string
        run: echo "Hello World!"
      - name: multiline script test
        run: |
          node -v
          php -v
